import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="border-b">
          <nav className="mx-auto max-w-5xl flex items-center gap-4 p-4 text-sm">
            <Link className="font-semibold" href="/">Tomorrow&apos;s Winner</Link>
            <Link href="/competitions">Competitions</Link>
            <Link href="/leaderboard">Leaderboards</Link>
            <Link href="/profile" className="ml-auto">Profile</Link>
            <Link href="/auth/sign-in">Sign in</Link>
          </nav>
        </header>
        <div className="mx-auto max-w-5xl">
          {children}
        </div>
      </body>
    </html>
  );
}
